### ISSUE TITLE
ssh-one

### ISSUE THREAD

**Issue by nicl** [guardian/prism#10]
Would be great to have an `ssh-one` function, which is similar to `ssh` but picks a random box to execute the command on.

The main motivation, for the CAPI team at least, is to execute commands against Elasticsearch clusters. E.g.

```
$ marauder ssh-one elasticsearch code -c 'curl -s localhost:9200/_cat/nodes'
```

This would be functionally equivalent to something like:

```
$ marauder -s elasticsearch code | head -n 1 | xargs -I HOST ssh HOST 'curl -s localhost:9200/_cat/nodes'
```

**Comment by katebee** [comment]
Does [ssm-scala](https://github.com/guardian/ssm-scala) cover this requirement?

More docs here: https://security-hq.gutools.co.uk/documentation/ssh-access

If we can use ssm-scala for this, can we close the issue?

**Comment by akash1810** [comment]
As [commented](https://github.com/guardian/prism/issues/10#issuecomment-392794128), this is now solved.
