### ISSUE TITLE
Add collector for server certificates?

### ISSUE THREAD

**Issue by cb372** [guardian/prism#29]
I'd like to make a tool to find certs that are close to expiry, and it seems like Prism might be the right tool for the job. If Prism collected all the certificates stored in IAM, along with their expiry dates, it would be trivial to write a tool that periodically queried Prism and alerted people.

The only potential problem is that certificates are not tagged with Stack/Stage/App, but maybe that's not an issue?

**Comment by sihil** [comment]
Closed by #30
